# Generated by Django 6.0.4 on 2026-04-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_groupexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='voice_assistant_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='voice_assistant_language',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
