# Generated by Django 6.0.4 on 2026-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userpreference_voice_assistant_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='enabled_languages',
            field=models.TextField(default='en-US,hi-IN'),
        ),
    ]
